[build]
  publish = "dist"
  command = "npm run build"

# Asset serving rules (must come before SPA fallback)
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/api/:splat"
  status = 200

# SPA fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), magnetometer=(), gyroscope=(), accelerometer=()"
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' blob:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https: blob:; connect-src 'self' https://*.supabase.co wss://*.supabase.co blob: data:; worker-src 'self' blob:; frame-ancestors 'none'; base-uri 'self'; form-action 'self';"

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Force HTML files to always check for updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Last-Modified = "Thu, 01 Jan 1970 00:00:00 GMT"
    ETag = "0"

# Force service worker to always check for updates
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Last-Modified = "Thu, 01 Jan 1970 00:00:00 GMT"
    ETag = "0"

# Force index.html to never be cached
[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
    Pragma = "no-cache"
    Expires = "0"
    Last-Modified = "Thu, 01 Jan 1970 00:00:00 GMT"
    ETag = "0"

# Cache manifest and other app files for short time
[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache favicons for short time
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=3600"

# Cache static assets (compression handled by Netlify automatically)
# Remove manual compression headers to avoid conflicts

# Resource hints (removed preload to avoid conflicts with SPA routing)

[build.environment]
  NODE_VERSION = "20"