[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets aggressively
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache HTML files for a short time to allow updates
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache manifest and other app files
[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Cache-Control = "public, max-age=86400"

# Cache favicons
[[headers]]
  for = "/favicon*"
  [headers.values]
    Cache-Control = "public, max-age=86400"

[build.environment]
  NODE_VERSION = "20"